def tax_relief_description() : 
    print ("1. Individual and dependent relatives [RM 9,000]")
    print ("2. Medical treatment, special needs and carer expenses for parents (Medical condition certified by medical practitioner)  [RM 8,000 (Restricted)]")
    print ("3. Purchase of basic supporting equipment for disabled self, spouse, child or parent [RM 6,000 (Restricted)]")
    print ("4. Disabled individual [RM 6,000]")
    print ("5. Education fees (Self) [RM 7,000 (Restricted)]:")
    print ("   - Other than a degree at masters or doctorate level - Course of study in law, accounting, islamic financing, technical, vocational, industrial, scientific or technology")
    print ("   - Degree at masters or doctorate level - Any course of study")
    print ("   - Course of study undertaken for the purpose of upskilling or self-enhancement (Restricted to RM2,000)")
    print ("[RM 10,000 (Restricted) for 6., 7. & 8.]")
    print ("6. Medical expenses on:")
    print ("     - Serious diseases for self, spouse or child")
    print ("     - Fertility treatment for self or spouse")
    print ("     - Vaccination for self, spouse and child (Restricted to RM1,000)")
    print ("7. Expenses (Restricted to RM1,000) on:")
    print ("     - Complete medical examination for self, spouse or child")
    print ("     - COVID-19 detection test including purchase of self-detection test kit for self, spouse or child")
    print ("     - Mental health examination or consultation for self, spouse or child")
    print ("8. Expenses (Restricted to RM4,000) for child aged 18 and below:")
    print ("     - Assessment of intellectual disability diagnosis")
    print ("     - Early intervention programme / intellectual disability rehabilitation treatment")
    print ("9. Lifestyle - Expenses for the use / benefit of self, spouse or child in respect of [RM 2,500 (Restricted)]:")
    print ("     - Purchase or subscription of books / journals / magazines / newspapers / other similar publications (Not banned reading materials)")
    print ("     - Purchase of personal computer, smartphone or tablet (Not for business use)")
    print ("     - Purchase of sports equipment for sports activity defined under the Sports Development Act 1997 and payment of gym membership")
    print ("     - Payment of monthly bill for internet subscription (Under own name)")
    print ("10.  Lifestyle - Additional relief for the use / benefit of self, spouse or child in respect of [RM 500 (Restricted)]:")
    print ("     - Purchase of sports equipment for any sports activity as defined under the Sports Development Act 1997")
    print ("     - Payment of rental or entrance fee to any sports facility")
    print ("     - Payment of registration fee for any sports competition where the organizer is approved and licensed by the Commissioner of Sports under the Sports Development Act 1997")
    print ("11. Purchase of breastfeeding equipment for own use for a child aged 2 years and below (Deduction allowed once in every TWO (2) years of assessment) [RM 1,000 (Restricted)]")
    print ("12. Child care fees to a registered child care centre / kindergarten for a child aged 6 years and below [RM 3,000 (Restricted)]")
    print ("13. Net deposit in Skim Simpanan Pendidikan Nasional (Net deposit is the total deposit in 2023 MINUS total withdrawal in 2023) [RM 8,000 (Restricted)]")
    print ("14. Husband / wife / payment of alimony to former wife [RM 4,000 (Restricted)]")
    print ("15. Disabled husband / wife [RM 5,000]")
    print ("16a. Each unmarried child and under the age of 18 years old [RM 2000]")
    print ("16b.  - Each unmarried child of 18 years and above who is receiving full-time education (""A-Level"", certificate, matriculation or preparatory courses).	[RM 2,000]")
    print ("      - Each unmarried child of 18 years and above that [RM 8000]:")
    print ("            i. receiving further education in Malaysia in respect of an award of diploma or higher (excluding matriculation/ preparatory courses).")
    print ("            ii. receiving further education outside Malaysia in respect of an award of degree or its equivalent (including Master or Doctorate).")
    print ("            iii. the instruction and educational establishment shall be approved by the relevant government authority.")
    print ("16c. - Disabled child [RM 6,000]")
    print ("        - Additional exemption of RM8,000 disable child age 18 years old and above, not married and pursuing diplomas or above qualification in Malaysia @ bachelor degree" +  
           "or above outside Malaysia in program and in Higher Education Institute that is accredited by related Government authorities [RM 8,000]")
    print ("17. Life insurance and EPF [RM 7000 (Restricted)]")
    print ("      Civil servants' pension schemes, non-civil servants pension schemes and self-employed category:")
    print ("       i. Mandatory contributions to approved schemes or voluntary contributions to EPF (excluding private retirement schemes) or contributions under any written law (Restricted to RM4,000)")
    print ("       ii. Life insurance premium payments or family takaful contributions or additional voluntary contributions to EPF (Restricted to RM3,000)")
    print ("18. Deferred Annuity and Private Retirement Scheme (PRS) [RM 3,000 (Restricted)]")
    print ("19. Education and medical insurance [RM 3,000 (Restricted)]")
    print ("20. Contribution to the Social Security Organization (SOCSO) [RM 350 (Restricted)]")
    print ("21. Expenses on charging facilities for Electric Vehicle (Not for business use) [RM 2,500 (Restricted)]")
    print ()
    print ("[RM XXXX or RM XXXX (Restricted)] represents the amount or upper limit of amount which could be claimed.")